services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
    command: start-single-node --insecure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  cockroachdb_data: