// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortCode   string
	Count       pgtype.Int4
	CreatedAt   time.Time
	DeletedAt   time.Time
	UpdatedAt   time.Time
}
