server:
  host: localhost
  port: 8000
  read_timeout: 10s
  read_header_timeout: 20s
  write_timeout: 20s
  idle_timeout: 10s
  max_header_bytes: 2MB
db:
  url: postgres://root@localhost:26257/defaultdb?sslmode=disable
  max_idle_time: 30s
migrations:
  file: internal/constant/query/schemas